on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        npm install
        npm run build --if-present
    - name: Testing
      run: npm run test:cov
    # - name: Generate release
    #   run: |
    #     git config --global user.email ci@nerdsletter.com
    #     git config --global user.name CI
    #     npm run release
    #     git push --follow-tags origin main
    - name: Get short image tag 
      id: slug
      run: echo "::set-output name=sha8::$(git rev-parse --short HEAD)"
    - name: Build and push docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tags: dev-${{ steps.slug.outputs.sha8 }}
    - name: Deploy to cluster
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: set image --record deployment/subscription  subscription=${{ github.repository }}:dev-${{ steps.slug.outputs.sha8 }}
    - name: Verify deployment 
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.15"
      with:
        args: '"rollout status deployment/subscription"'
